export const C = {
	CANCEL_EDIT: "CANCEL_EDIT",
	CONFIRM_DELETE: "CONFIRM_DELETE",
	DELETE_TEXT: "DELETE_TEXT",
	PUBLISH_TEXT: "PUBLISH_TEXT",

	DELETE_COMMENT: "DELETE_COMMENT",

	// Search parameters
	TAGS: "TAGS",
	USERS: "USERS",
	TITLES: "TITLES",

	MORE_OPTIONS: "MORE_OPTIONS",
}