export const URL = {
	SERVER: import.meta.env.VITE_BACKEND_URL,
	NEW_TEXT: "/new_text",
	TEXT: "/text/",
	TEXTS: "/texts",
	TAG: "/tag/",
	TAGS: "/tags",
	SEARCH_TAGS: "/search_tags",
	UPDATE_PROFILE: "/update_profile",
	PROFILE: "/profile/",
	SERIES: "/series_id/",
	COLLECTIVE: "/collective/",
	LIKE: "/like/",
	UNLIKE: "/unlike/",
	LIKE_COMMENT: "/like_comment/",
	UNLIKE_COMMENT: "/unlike_comment/",
	BOOKMARK: "/bookmark/",
	UNBOOKMARK: "/unbookmark/",
	SUBSCRIBE: "/subscribe/",
	UNSUBSCRIBE: "/unsubscribe/",
	COMMENT: "/comment/",
	AUTH:"/auth",
	LOGIN: "/login",
	LOGOUT: "/logout",
	SIGNUP: "/signup",
	USER_DATA: "/user_data",
}