export const URL = {
	SERVER: "http://localhost:8000",

	NEW_TEXT: "/new_text",
	TEXT: "/text/",
	TEXTS: "/texts",
	TAG: "/tag/",
	TAGS: "/tags",
	SEARCH_TAGS: "/search_tags",
	UPDATE_PROFILE: "/update_profile",
	PROFILE: "/profile/",
	SERIES: "/series_id/",
	COLLECTIVE: "/collective/",
	LIKE: "/like/",
	UNLIKE: "/unlike/",
	BOOKMARK: "/bookmark/",
	UNBOOKMARK: "/unbookmark/",
	SUBSCRIBE: "/subscribe/",
	UNSUBSCRIBE: "/unsubscribe/",
	COMMENT: "/comment/",
}