# Generated by Django 4.2.4 on 2024-11-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='likes',
        ),
    ]
