# Generated by Django 4.2.4 on 2024-11-06 15:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunko', '0002_remove_text_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='likes',
            field=models.ManyToManyField(related_name='likes', through='bunko.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
