# Generated by Django 4.2.4 on 2024-11-06 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0003_text_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
