# Generated by Django 4.2.4 on 2024-11-07 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bunko', '0004_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_text', to='bunko.text'),
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_text', to='bunko.text')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
