# Generated by Django 4.2.4 on 2024-11-28 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0006_series_text_series_entry_text_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='tag',
        ),
    ]
