# Generated by Django 4.2.4 on 2024-11-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0007_rename_name_genre_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='synopsis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
