# Generated by Django 4.2.4 on 2024-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0008_text_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='synopsis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='synopsis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
