# Generated by Django 4.2.4 on 2024-12-03 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='liked_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
