# Generated by Django 4.2.4 on 2024-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0011_like_liked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
