# Generated by Django 4.2.4 on 2024-12-20 17:02

from django.db import migrations
import nanoid_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0012_text_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='hash',
            field=nanoid_field.fields.NanoidField(alphabet='0123456789abcdefghijklmnopqrstuvwxyz', max_length=21),
        ),
    ]
