# Generated by Django 4.2.4 on 2025-01-15 17:13

from django.db import migrations, models
import nanoid_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0013_text_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='picture',
            field=models.ImageField(blank=True, default='default-bunko.jpg', null=True, upload_to='series_cover'),
        ),
        migrations.AlterField(
            model_name='text',
            name='hash',
            field=nanoid_field.fields.NanoidField(alphabet='0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz', max_length=21),
        ),
        migrations.AlterField(
            model_name='text',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
