# Generated by Django 4.2.4 on 2025-01-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0014_alter_series_picture_alter_text_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='picture',
        ),
    ]
