# Generated by Django 5.1.6 on 2025-02-21 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0015_remove_series_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='genres',
            field=models.ManyToManyField(related_name='text_genres', to='bunko.genre'),
        ),
        migrations.AlterField(
            model_name='text',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text', to='bunko.series'),
        ),
    ]
