# Generated by Django 5.1.6 on 2025-03-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bunko', '0019_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='bookmark_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
