# Generated by Django 4.2.4 on 2024-11-05 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='default-bunko.jpg', upload_to='profile_pics')),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('subcription_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscribers', models.ManyToManyField(to='users.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
