# Generated by Django 4.2.4 on 2024-11-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscribers',
            field=models.ManyToManyField(through='users.Subscription', to='users.profile'),
        ),
    ]
