# Generated by Django 4.2.4 on 2024-11-06 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subcription_date',
            new_name='subscription_date',
        ),
    ]
