# Generated by Django 4.2.4 on 2024-11-06 17:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_subcription_date_profile_subscription_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='subscription_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='signup_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
