# Generated by Django 4.2.4 on 2024-11-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_subscription_date_profile_signup_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscribers',
            new_name='followers',
        ),
    ]
