# Generated by Django 4.2.4 on 2024-11-06 17:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0007_rename_subscribers_profile_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='followed_by',
            new_name='follower',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='followee',
        ),
        migrations.AddField(
            model_name='subscription',
            name='following',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
