# Generated by Django 4.2.4 on 2024-11-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_followed_by_subscription_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='followers',
        ),
    ]
