# Generated by Django 4.2.4 on 2024-12-02 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_alter_subscription_follower_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('picture', models.ImageField(default='default-bunko.jpg', upload_to='profile_pics')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collective_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_starred_member', models.BooleanField(default=False)),
                ('collective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collective', to='users.collective')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='users.profile')),
            ],
        ),
        migrations.AddField(
            model_name='collective',
            name='members',
            field=models.ManyToManyField(related_name='members', through='users.Membership', to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='collectives',
            field=models.ManyToManyField(related_name='collectives', through='users.Membership', to='users.collective'),
        ),
    ]
