# Generated by Django 4.2.4 on 2024-12-03 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_collective_membership_collective_members_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='collectives',
        ),
        migrations.AlterField(
            model_name='collective',
            name='members',
            field=models.ManyToManyField(related_name='members', through='users.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL),
        ),
    ]
